env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:unicorn/recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  camelcase: 1
  jsx-a11y/label-has-associated-control: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.js'
        - '.jsx'
  react/prop-types: 0
  react/no-danger: 0
  react/jsx-one-expression-per-line: 0
  unicorn/filename-case: 0
  unicorn/prevent-abbreviations: 0
  prettier/prettier:
    - error
    - arrowParens: avoid
      bracketSpacing: true
      endOfLine: lf
      htmlWhitespaceSensitivity: css
      jsxBracketSameLine: false
      jsxSingleQuote: false
      parser: babel
      printWidth: 80
      proseWrap: preserve
      requirePragma: false
      semi: true
      singleQuote: true
      tabWidth: 2
      trailingComma: es5
      useTabs: false
      vueIndentScriptAndStyle: true
      overrides:
      - files: "*.json"
        options:
          printWidth: 200
