arrowParens: avoid
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: css
jsxBracketSameLine: false
jsxSingleQuote: false
parser: babel
printWidth: 80
proseWrap: preserve
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
vueIndentScriptAndStyle: true
overrides:
- files: "*.json"
  options:
    printWidth: 200
