backend:
  name: github
  repo: tumbleweird/vote.triciti.es
  branch: master

local_backend: true

publish-mode: editorial_workflow

media_folder: 'static/images'
public_folder: 'images'

collections:
  - name: candidates
    media_folder: '/{{media_folder}}/candidates'
    public_folder: '/{{public_folder}}/candidates'
    identifier_field: name
    label_singular: Candidate
    label: Candidates
    folder: data
    slug: '{{region}}-{{office}}-{{fields.slug}}'
    extension: json
    create: true
    fields:
      - { name: name, label: Name }
      - {
          name: region,
          label: Region,
          widget: select,
          required: true,
          options:
            [
              { label: 'District 8', value: 'district-8' },
              { label: 'District 9', value: 'district-9' },
              { label: 'District 16', value: 'district-16' },
              { label: 'Benton County', value: 'benton' },
              { label: 'Franklin County', value: 'franklin' },
              { label: 'Benton/Franklin', value: 'bf'}
            ],
        }
      - {
          name: office,
          label: Office,
          widget: select,
          options:
            [
              { label: 'County Commissioner District 1', value: 'commissioner-1' },
              { label: 'County Commissioner District 2', value: 'commissioner-2' },
              { label: 'County Commissioner District 3', value: 'commissioner-3' },
              { label: 'State Senator', value: 'wa-senator' },
              { label: 'State Representative Pos 1', value: 'wa-rep-1' },
              { label: 'State Representative Pos 2', value: 'wa-rep-2' },
              { label: 'Superior Court Judge', value: 'judge' },
              { label: 'U.S. Representative', value: 'congress' },
            ],
          required: true,
        }
      - { name: image, label: Image, widget: image, required: false }  
      - { name: bio, label: Short bio, widget: markdown }
      - { name: email, label: Email, required: false }
      - { name: statement, label: Statement, required: false }
      - { name: website, label: Website, required: false }
      - { name: facebook, label: Facebook, required: false }
      - { name: twitter, label: Twitter, required: false }
      - { name: pdc, label: Campaign Finance, required: true }
      - { name: lettersyes, label: Letters Yes / Endorsements, widget: markdown, required: false }
      - { name: lettersno, label: Letters No, widget: markdown, required: false }
      - { name: articles, label: Articles, widget: markdown, required: false }
      - { name: body, label: Body, widget: markdown }